print("Welcome to the tip calculator")
bill=float(input("What was the total bill?"))
people=int(input("How many people to split the bill?"))
percentage=int(input("What percentage tip would you like to give? 10, 12 0r 15?"))
print("Each person should pay:")